import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header, Footer, BottomBadges } from "./components";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CHFoundation",
  description: "Generated by create next app",
  icons: {
    icon: '/logo-favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main>{children}</main>
        <BottomBadges />
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
